# Generated by Django 3.1.3 on 2022-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, max_length=10)),
                ('sub_total', models.FloatField(default=0.0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('Accept', 'Accepted'), ('Reject', 'Rejected'), ('Pending', 'Pending'), ('Dispatch', 'Dispatched'), ('Cancel', 'Cancelled'), ('Delivered', 'Delivered')], default='Pending', max_length=10)),
                ('total_price', models.FloatField(default=0.0)),
                ('payment_id', models.CharField(default='', max_length=30)),
                ('payment_status', models.CharField(choices=[('None', 'None'), ('Paid', 'Paid'), ('RefundInit', 'RefundInit'), ('Refunded', 'Refunded')], default='None', max_length=20)),
                ('coupon_code', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
