# Generated by Django 3.1.3 on 2022-07-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('strip', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(max_length=50)),
                ('ingredients', models.JSONField(default='')),
                ('manufactured_by', models.CharField(default='', max_length=20)),
                ('marketed_by', models.CharField(default='', max_length=20)),
                ('price', models.CharField(default=0.0, max_length=10)),
                ('description_2', models.TextField(default='', max_length=50)),
                ('description_3', models.TextField(default='', max_length=50)),
                ('stock_status', models.CharField(choices=[('InStock', 'InStock'), ('OutStock', 'OutOfStock')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_products', models.JSONField(default='')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
